[package]
name = "ebc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ebclib = {path = "../ebclib"}

[[bin]]
name = "ebc2024q01"

[[bin]]
name = "ebc2024q02"

[[bin]]
name = "ebc2024q03"

[[bin]]
name = "ebc2024q04"

[[bin]]
name = "ebc2024q05"

[[bin]]
name = "ebc2024q06"

